#spring:
#  datasource:
#    url: String url ="jdbc:mysql://travel-service.mysql.database.azure.com:3306/{travel-service}?useSSL=true&requireSSL=false"; myDbConn = DriverManager.getConnection(url, "kienpt@travel-service", {70ltd_ptkm*888});
#    username: kienpt
#    password: 70ltd_ptkm*888
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      dialect : org.hibernate.dialect.MySQL5InnoDBDialect
#
#server:
#  port: 9191