#spring:
##  datasource:
##    url: jdbc:mysql://travel-service.mysql.database.azure.com:3306/travelservices?verifyServerCertificate=false&useSSL=TRUE
##    username: kienpt@travel-service
##    password: 70ltd_ptkm*888
##  jpa:
##    show-sql: true
##    hibernate:
##      ddl-auto: update
##      dialect : org.hibernate.dialect.MySQL5InnoDBDialect
##  mail:
##      host: smtp.gmail.com
##      port: 587
##      username: kienpt375@gmail.com
##      password: ctypmityywseoaol
##      properties:
##        mail:
##          smtp:
##            auth: true
##            starttls:
##              enable: true
##              required: true
##server:
##  port: 9191